apps/follow/urls.py
from django.urls import path
from .import views




app_name = 'follow'

urlpatterns = [
    path('toggle/',views.follow_toggle,name='follow-toggle'),
]

apps/post/urls.py
from django.urls import path
from .import views


app_name = 'post'

urlpatterns = [
    path('like-unlike/',views.post_like_unlike,name='post-like-unlike'),
    path('add/',views.post_add,name='post_add'),
    path('detail/<str:slug>/',views.post_view,name='post-view'),
    path('delete/<str:slug>/',views.post_delete,name='post-delete'),
]

apps/report/urls.py
from django.urls import path
from .import views




app_name = 'report'

urlpatterns = [
    path('create/<str:slug>/',views.report_post,name='report-post'),
]

apps/search/urls.py
from django.urls import path
from .import views




app_name = 'search'

urlpatterns = [
    path('',views.search_user,name='query'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

from .import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index_view,name='index'),
    path('oauth/',include('social_django.urls',namespace='social')),
    path('account/',include('apps.account.urls',namespace='account')),
    path('comment/',include('apps.comment.urls',namespace='comment')),
    path('follow/',include('apps.follow.urls',namespace='follow')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('report/',include('apps.report.urls',namespace='report')),
    path('post/',include('apps.post.urls',namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# handler404 = TemplateView.as_view(template_name='404.html')
# handler400 = TemplateView.as_view(template_name='400.html')
# handler500 = TemplateView.as_view(template_name='500.html')
# handler403 = TemplateView.as_view(template_name='403.html')

templates/partials/_followers_modal.html
<!-- Modal -->
{% load static from staticfiles %}
<div class="modal fade" id="exampleModalScrollableFollower" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content modal-sizing">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Followers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-scrollable-activate">
       {% if user_followers %}
          <ul class="list-group list-group-flush">
            {% for user_f in user_followers %}
              <li class="list-group-item clearfix">
                {% if user_f.profile.pic %}
                <img class='modal-avatar--img' src="{{user_f.profile.pic_url}}" alt="user_f.username dp">
                {% else %}
                <img class='modal-avatar--img' src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="default-avatar dp">
                {% endif %}
                <span><a href="{{user_f.profile.get_absolute_url}}">{{user_f.username}}</a></span>
                  {% if request.user != user_f %}
                   <form action="{% url 'follow:follow-toggle' %}" method="POST" class="follow-form-avatar follow-avatar--btn" style="display: inline;">
                      {% csrf_token %}
                      <input type="hidden" name="to_user" value="{{user_f.username}}">
                      {% if is_auth %}
                        {% if request.user in user_f.profile.user_followers %}
                        <button class="btn float-right btn-default btn--unfollow">UnFollow</button>
                        {% else %}
                        <button class="btn float-right btn-default btn--follow">Follow</button>
                        {% endif %}
                      {% endif %}
                  </form>
                  {% endif %}
              </li>
            {% endfor %}
          </ul>
       {% else %}
       <p>No Followers</p>
       {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Close Modal -->

templates/partials/_followings_modal.html
{% load static from staticfiles %}
<!-- Modal -->
<div class="modal fade" id="exampleModalScrollableFollowing" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content modal-sizing">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Followings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-scrollable-activate">
       {% if user_followings %}
          <ul class="list-group list-group-flush">
            {% for user_ff in user_followings %}
              <li class="list-group-item clearfix">
                {% if user_ff.profile.pic %}
                <img class='modal-avatar--img' src="{{user_ff.profile.pic_url}}" alt="user_ff.username dp">
                {% else %}
                <img class='modal-avatar--img' src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="default-avatar dp">
                {% endif %}
                <span><a href="{{user_ff.profile.get_absolute_url}}">{{user_ff.username}}</a></span>
               <!--  <form action="" method="" class="modal-follow-form">
                  {% csrf_token %}
                 <button class="btn btn-primary float-right btn-follow-modal">Follow</button>
                </form> -->
                  <form action="{% url 'follow:follow-toggle' %}" method="POST" class="follow-form-avatar follow-avatar--btn" style="display: inline;">
                      {% csrf_token %}
                      <input type="hidden" name="to_user" value="{{user_ff.username}}">
                      {% if is_auth %}
                        {% if request.user in user_ff.profile.user_followers %}
                        <button class="btn float-right btn-default btn--unfollow">UnFollow</button>
                        {% else %}
                        <button class="btn float-right btn-default btn--follow">Follow</button>
                        {% endif %}
                      {% endif %}
                  </form>
              </li>
            {% endfor %}
          </ul>
       {% else %}
       <p>No Followings</p>
       {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Close Modal -->

templates/partials/_nav.html
{% load static from staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm app-nav fixed-top">
<div class="container-fluid nav--container-padding">
  <a class="navbar-brand " href="/">
    <img class='logo-img-tag' src="{% static 'images/logo/logo.png' %}" alt="" style="    height: 33px;
    width: auto;
    max-width: 100%;">
  </a>
  <form class="form-inline" action="{% url 'search:query' %}" method="">
    {% csrf_token %}
    <input class="form-control ml-sm-2 search-query" type="search" name="query" value="{{request.query}}" placeholder="Search for people ...">
  </form>
  <div class="collapse navbar-collapse " id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      {% if is_auth %}
      <li class="nav-item active">
        <a class="nav-link" href="#">Ads<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="#">Jobs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Forum</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="la la-user-circle" style="font-size: 19px;"></i>
        </a>
        {% if request.user.is_authenticated %}
        <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{request.user.profile.get_absolute_url}}">profile</a>
          <a class="dropdown-item" href="#">change password</a>
          <a class="dropdown-item" href="{% url 'account:logout' %}">logout</a>
        </div>
        {% else %}
        <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'account:auth' %}">Sign Up</a>
          <a class="dropdown-item" href="{% url 'account:auth' %}">Sign In</a>
        </div>
        {% endif %}
      </li>
    </ul>
  </div>
 </div>
</nav>

templates/partials/_post_report_modal.html
<!-- modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Report Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'report:report-post' post.slug %}" method="POST" class="text-center">
          {% csrf_token %}
        	<label><input type="radio" name="report_radio" value="1">It's spam</label>
        	<label><input type="radio" name="report_radio" value="2">Inappropriate</label>
          <label><input type="radio" name="report_radio" value="3">False information</label>
          <div>
            <button class="btn btn-primary">Report</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

templates/partials/_top_comments_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Top Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-scrollable-activate">
        Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

		Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.

		Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.

		Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
      </div>
    </div>
  </div>
</div>

templates/partials/post_add_form_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModalScrollablePOST" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Add a Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-scrollable-activate">
        <div class="row">
    <div class="col-md-12" style="z-index: 111111111111;position: static;">
      <!-- form starts here -->
        <form method="POST" action="{% url 'post:post_add' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="post_owner" value="{{ request.user.username }}">
            <div class="row">
                <div class="col-sm-12 form-group">
                    <label for="email">
                        Title : </label>
                    <input type="text" class="form-control" id="title_id" name="title"
                    maxlength="50" required="required">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <label for="name">
                        Content:</label>
                    <textarea class="form-control" type="textarea" id="content_id" name="content" placeholder="Your Post Content here..." maxlength="400" rows="4" required="required"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <input type="file" class="form-control" name="file" id="file_id" style="border:transparent;">
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 form-group">
                    <button type="submit" class="btn btn-info btn-block shadow-sm">Post it !</button>
                </div>
            </div>
        </form>
        <!-- close form -->
    </div>
</div>
      </div>
    </div>
  </div>
</div>