apps/comment/urls.py
from django.urls import path
from .import views




app_name = 'comment'

urlpatterns = [
    path('add/',views.comment_add,name='comment-add'),
    path('remove/',views.comment_remove,name='comment-remove'),
]

apps/follow/urls.py
from django.urls import path
from .import views




app_name = 'follow'

urlpatterns = [
    path('toggle/',views.follow_toggle,name='follow-toggle'),
]

apps/post/urls.py
from django.urls import path
from .import views


app_name = 'post'

urlpatterns = [
    path('like-unlike/',views.post_like_unlike,name='post-like-unlike'),
    path('add/',views.post_add,name='post_add'),
    path('detail/<str:slug>/',views.post_view,name='post-view'),
    path('delete/<str:slug>/',views.post_delete,name='post-delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

from .import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index_view,name='index'),
    path('oauth/',include('social_django.urls',namespace='social')),
    path('account/',include('apps.account.urls',namespace='account')),
    path('comment/',include('apps.comment.urls',namespace='comment')),
    path('follow/',include('apps.follow.urls',namespace='follow')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('report/',include('apps.report.urls',namespace='report')),
    path('post/',include('apps.post.urls',namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# handler404 = TemplateView.as_view(template_name='404.html')
# handler400 = TemplateView.as_view(template_name='400.html')
# handler500 = TemplateView.as_view(template_name='500.html')
# handler403 = TemplateView.as_view(template_name='403.html')

apps/post/models.py
from django.utils import timezone

from apps.common.utils import photo_file_loc,human_readable_time

from django.core.exceptions import PermissionDenied
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils.text import Truncator
from django.http import Http404
from django.conf import settings
from django.urls import reverse

from django.db import models



class Post(models.Model):

	owner					= models.ForeignKey(to=settings.AUTH_USER_MODEL,
												related_name='posts',
												on_delete=models.CASCADE)

	title 					= models.CharField(max_length=125,blank=True,null=True)
	content					= models.TextField(max_length=250)
	slug 					= models.SlugField(max_length=125,unique=True,null=True,blank=True)
	photo					= models.ImageField(upload_to=photo_file_loc,blank=True,null=True,default='')

	users_like				= models.ManyToManyField(to=settings.AUTH_USER_MODEL,
													related_name='post_liked',
													blank=True)
	total_likes				= models.PositiveSmallIntegerField(default=0)
	views 					= models.PositiveSmallIntegerField(default=0,blank=True,null=True)

	created					= models.DateTimeField(auto_now_add=True)
	updated					= models.DateTimeField(auto_now=True)


	class Meta:
		ordering 			= ('-created',)
		verbose_name		= 'Post'
		verbose_name_plural = 'Posts'


	def __str__(self):
		return '{0}'.format(self.title)


	@property
	def get_absolute_url(self):
		return reverse('post:post-view',args=[str(self.slug)])
	

	@property
	def created_by(self):
		return self.owner.username
	

	@property
	def created_at(self):
		return human_readable_time(self.created)


	@property
	def pic(self):
		if self.photo:
			return self.photo.url
		return

	pic_url = pic


	@property
	def comments_count(self):
		return self.comments.count() if self.comments else 0


	@property
	def post_comments(self):
		return self.comments.all()
	


	@property
	def recent_post_comment(self):
		qry = self.comments.first()
		return qry

	@property
	def more_comments(self):
		qry = self.comments.all()
		if qry.exists():
			if qry.count() > 1:
				return True
			elif qry.count() == 1:
				return False
		return False
	


	@property
	def likes_count(self):
		return self.total_likes


	@property
	def post_users_like(self):
		return self.users_like.all()
	
	
	

apps/post/forms.py
from django import form
from .models import Post



class PostCreateForm(forms.ModelForm):
	class Meta:
		model 	= Post
		fields	= ('title','content','photo',)

apps/post/views.py
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from apps.common.decorators import ajax_required
from django.contrib.auth import get_user_model
from django.shortcuts import render,redirect
from django.http import Http404
from django.urls import reverse

from apps.post.models import Post
from apps.activity import utils



@ajax_required
@login_required
@require_http_methods(["POST"])
def post_like_unlike(request):
	user = request.user
	post_id = request.POST.get('post_id');
	post    = get_object_or_404(Post,id = post_id)
	is_liked = None
	if request.user in post.users_like.all():
		post.users_like.remove(request.user)
		is_liked = False
	else:
		is_liked = True
		post.users_like.add(request.user)
		utils.create_action(user,'likes',post)
	likes_count = post.likes_count
	return JsonResponse({'liked':is_liked,'likes_count':likes_count})



@login_required
def post_add(request):
	if request.method == 'POST' and request.FILES['file']:
		username = request.POST.get('post_owner')
		owner 	= get_object_or_404(get_user_model(),username__iexact=username.strip())
		title = request.POST.get('title')
		content = request.POST.get('content')
		file 	= request.FILES.get('file')
		# TODO : validate user input & files( size,format,dimensions,ip(optional))
		post_instance,_ = Post.objects.\
		get_or_create(owner = owner,
		title = title,
		content = content,
		photo = file)
		utils.create_action(owner,'added a new post',post_instance)
		return redirect(reverse('account:user-profile',kwargs={'username':owner.username}))
	else:
		pass



def viewed_by_session(request,post_obj):
	session_key = 'viewed_topic_{}'.format(post_obj.id)
	if not request.session.get(session_key,False):
		post_obj.views += 1
		post_obj.save()
		request.session[session_key] = True


def post_view(request,slug = None):
	if not slug is None:
		post_instance = get_object_or_404(Post,slug = slug.strip())
		viewed_by_session(request,post_instance)
		comments = post_instance.post_comments
	return render(request,'post/post_detail_view.html',
		{'post':post_instance,
		'comments':comments})



@login_required
def post_delete(request,slug):
	# only post owners and superusers or admin can delete post
	return HttpResponse(slug)

templates/post/index_ajax.html
{% load static from staticfiles %}
		
					{% for post in posts %}
						 <div class="card shadow-sm middle-content-card post-space--bottom"><!-- card starts -->
						    	<div class="post-card-top-avatar-wrap clearfix">
						    		{% if post.owner.profile.pic %}
						    		<img src="{{post.owner.profile.pic_url }}" alt="..." class="avatar-sizing rounded-circle">
						    		{% else %}
						    		<img src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="..." class="avatar-sizing rounded-circle">
						    		{% endif %}
						    		<h5 style="display: inline-block;"><a href="{{post.owner.profile.get_absolute_url}}">{{post.created_by}}</a></h5>
						    		<span class="post-create-at">{{ post.created_at}}</span>
						    		{% ifnotequal request.user post.owner %}
						    		<div class="btn--follow-wrap float-right pt-3" style="display: inline-block;">
						    			<form action="{% url 'follow:follow-toggle' %}" method="POST" class="follow-form-avatar follow-avatar--btn">
						    			{% csrf_token %}
						    			<input type="hidden" name="to_user" value="{{post.owner.username}}">
						    			{% if is_auth %}
						    				{% if request.user in post.owner.profile.user_followers %}
						    				<button class="btn btn-default btn--unfollow">UnFollow</button>
						    				{% else %}
						    				<button class="btn btn-default btn--follow">Follow</button>
						    				{% endif %}
						    			{% endif %}
						    			</form>
						    		</div>
						    		{% endifnotequal %}

						    	</div>
						    <div  class='post--card-wrap'>
						    	<a href="{% url 'post:post-view' post.slug %}" style="text-decoration: none;color:#565656;">
						    	{% if post.pic %}
								    <img src="{{post.pic}}" class="card-img-top" alt="...">
								    {% endif %}
								    <div class="card-body">
								      <h5 class="card-title">{{post.title}}</h5>
								      <p class="card-text">{{post.content}}</p>
								    </div>
								</a>
							</div>
							<div class="card-footer parent-wrap" style="background: #fff;padding:.75rem 0 !important">
						      <div class="clearfix like-comment-report-wrap-div">
						      	<p class="like-para">
						      		<i class="la la-thumbs-up la-thumbs-up--circle"></i>
						      		<span>{{post.likes_count}}</span>
						      	</p>
						      	<span>.</span>
						      	<p class="comment-para">
						      		<i class="la la-comments la-comments-icon"></i>
						      		<span>{{post.comments_count}}</span>
						      	</p>
						      	<p class="comment-para views-wrap-p">
						      		<span>views</span>
						      		<span>{{ post.views }}</span>
						      	</p>
						      	
						      	{% if is_auth %}
						      	<p class="float-right report--3-dots" data-toggle="modal" data-target="#exampleModal">
						      		<span>...</span>
						      	</p>
						      	{% endif %}
						      	
						      	<!-- modal -->
						      	{% include "partials/_post_report_modal.html" with post=post %}
						      	<!-- /modal here -->
						      </div>
						      <div class="card-divider-comments"></div>
						      <div class="like-comment-action-icon-div">
						      	{% if is_auth %}
						      	<form action="{% url 'post:post-like-unlike' %}" method="POST" class="like-form">
						      		{% csrf_token %}
						      		<input type="hidden" name="post_id" value="{{post.id}}">
						      		<button>
						      			{% if request.user in post.post_users_like %}
						      			<i class='la la-thumbs-down la-like--action-icon unliked'></i>
						      			{% else %}
						      			<i class='la la-thumbs-up la-like--action-icon liked'></i>
						      			{% endif %}
						      		</button>
						      		<span class="like-text icon-text">Like</span>
						      	</form>
						      	{% else %}
						      	<form action="" method="" class="like-form">
						      		<button>
						      			<i class='la la-thumbs-up la-like--action-icon unliked'></i>
						      		</button>
						      		<span class="like-text icon-text">Like</span>
						      	</form>
						      	{% endif %}
						      	<span class="action-comment-span space-action-span comment-action-js">
						      		<i class='la la-comments la-comment-action-icon'></i>
						      		<span class="comment-text icon-text">Comment</span>
						      	</span>
						      	<span class="action-share-span space-action-span">
						      		<i class='la la-share la-comment-action-icon'></i>
						      		<span class="share-text icon-text">Share</span>
						      	</span>

						      	<span class="float-right icon-text" data-toggle="modal" data-target="#exampleModalScrollable">Top Comments<i class='la la-caret-down'></i></span>
						      </div>
						      {% include 'partials/_top_comments_modal.html' %}
						      <!-- comment form div -->
						   {% if is_auth %}
						  	<div class="comment-form-div hide-comment-form-wrap">
						      	<div class="container-fluid comment-container--fluid-padding">
						      		<div class="row">
						      			<div class="col col-lg-2">
						      				{% if request.user.profile.pic %}
						      				<img src="{{request.user.profile.pic_url}}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% else %}
						      				<img src="{% static 'images/request_user.png' %}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% endif %}
							      		</div>
						      			<div class="col col-lg-10">
						      				<form class="form-inline my-2 my-lg-0 comment-form" action="{% url 'comment:comment-add' %}" method="POST">
						      					{% csrf_token %}
						      					<!-- <div class="col-lg-12"> -->
						      						<input type="hidden" name="post_id" value="{{post.id}}">
								      				<input class="form-control mr-sm-2 form-control-lg comment-input" type="search" placeholder="Add a comment...">
								      			<!-- </div> -->
								    		</form>
						      			</div>
						      		</div>
						      		{% if post.recent_post_comment %}
						      		<div class="row space-posts-comments-by-users">
						      			<div class="col col-lg-2">
						      				{% if post.recent_post_comment.user.profile.pic %}
						      				<img src="{{post.recent_post_comment.user.profile.pic_url}}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% else %}
						      				<img src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% endif %}
							      		</div>
						      			<div class="col col-lg-10">
						      				<div>
						      						{% if post.recent_post_comment.user%}
						      						<h6>
						      					      <a href="{{post.owner.profile.get_absolute_url}}"> {{post.recent_post_comment.user.username}}</a>
						      				    	</h6>
						      				        {%endif%}
						      					<div class="post-comment-text-wrap clearfix">
						      						<p>
						      							{{post.recent_post_comment.content}}
						      						</p>
						      						<p class="float-right">{{ post.recent_post_comment.readable_time }}</p>
						      					</div>
						      					{% if post.more_comments %}
						      					<p><a href="#">view all comments</a></p>
						      					{% endif %}
						      				</div>
						      			</div>				      			
						      		</div>
						      		{% endif %}
								</div>
						      </div>
						      {% endif %}
						      <!-- close comment form div -->
						    </div>
						  </div><!-- card end -->
				  	{% endfor %}

templates/post/post_detail_view.html
{% extends 'layout.html' %}
{% load static from staticfiles %}


{% block css %}
        
.comment-content{
	display:inline-block;

}


.comment-content p{
	display:inline-block;
	width:auto;
}

.comment-content p > span.time-reads{
	font-weight: 100;
    font-size: 13px;
	display:inline-block;
	margin-left:1.2em;
}

.card--title{
	padding:5px;
}

.card--title h4{
	font-weight:400;
}

.card-body{
	border-bottom: 1px solid rgba(0,0,0,0.12);
	<!-- border-top: 1px solid rgba(0,0,0,0.12); -->
}

.comment-underline{
    width: 15%;
    height: 5px;
    background: #39a6b1;
    margin: 0 0 1em 15px;;
    border-radius: 25px;
}

.comment-content p.username-parag{
	font-weight: 600;
	font-size: 18px;
	display: block;
	margin-bottom: 0 !important;
	text-transform: capitalize;
}

.badge-danger {
    color: #fff;
    background-color: #ff7e8b;
    font-weight: 100;
}

.comment-remove-form button{
	outline: none;
    border: none;
    padding: 5px;
}

.no-comments{
	padding: 4px 0 0 10px;
    font-weight: 100;
}

{% endblock %}

{% block content %}
<div class="container-fluid container--fluid--wrap">
	<div class="row">
		<div class="col-lg-5 offset-lg-1">
					 <div class="card shadow-sm middle-content-card post-space--bottom"><!-- card starts -->
						    	<div class="post-card-top-avatar-wrap clearfix">
						    		{% if post.owner.profile.pic %}
						    		<img src="{{post.owner.profile.pic_url }}" alt="..." class="avatar-sizing rounded-circle">
						    		{% else %}
						    		<img src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="..." class="avatar-sizing rounded-circle">
						    		{% endif %}
						    		<h5 style="display: inline-block;"><a href="{{post.owner.profile.get_absolute_url}}">{{post.created_by}}</a></h5>
						    		<span class="post-create-at">{{ post.created_at}}</span>
						    		{% ifnotequal request.user post.owner %}
						    		<div class="btn--follow-wrap float-right pt-3" style="display: inline-block;">
						    			<form action="{% url 'follow:follow-toggle' %}" method="POST" class="follow-form-avatar follow-avatar--btn">
						    			{% csrf_token %}
						    			<input type="hidden" name="to_user" value="{{post.owner.username}}">
						    			{% if is_auth %}
						    				{% if request.user in post.owner.profile.user_followers %}
						    				<button class="btn btn-default btn--unfollow">UnFollow</button>
						    				{% else %}
						    				<button class="btn btn-default btn--follow">Follow</button>
						    				{% endif %}
						    			{% endif %}
						    			</form>
						    		</div>
						    		{% endifnotequal %}

						    	</div>
						    <div  class='post--card-wrap'>
						    	<a href="{% url 'post:post-view' post.slug %}" style="text-decoration: none;color:#565656;">
						    	{% if post.pic %}
								    <img src="{{post.pic}}" class="card-img-top" alt="...">
								    {% endif %}
								    <div class="card-body">
								      <h5 class="card-title">{{post.title}}</h5>
								      <p class="card-text">{{post.content}}</p>
								    </div>
								</a>
							</div>
							<div class="card-footer parent-wrap" style="background: #fff;padding:.75rem 0 !important">
						      <div class="clearfix like-comment-report-wrap-div">
						      	<p class="like-para">
						      		<i class="la la-thumbs-up la-thumbs-up--circle"></i>
						      		<span>{{post.likes_count}}</span>
						      	</p>
						      	<span>.</span>
						      	<p class="comment-para">
						      		<i class="la la-comments la-comments-icon"></i>
						      		<span>{{post.comments_count}}</span>
						      	</p>
						      	<p class="comment-para views-wrap-p">
						      		<span>views</span>
						      		<span>{{ post.views }}</span>
						      	</p>
						      	
						      	{% if is_auth %}
						      	<p class="float-right report--3-dots" data-toggle="modal" data-target="#exampleModal">
						      		<span>...</span>
						      	</p>
						      	{% endif %}
						      	<!-- modal -->
						      	{% include "partials/_post_report_modal.html" with post=post %}
						      	<!-- /modal here -->
						      </div>
						      <div class="card-divider-comments"></div>
						      <div class="like-comment-action-icon-div">
						      	{% if is_auth %}
						      	<form action="{% url 'post:post-like-unlike' %}" method="POST" class="like-form">
						      		{% csrf_token %}
						      		<input type="hidden" name="post_id" value="{{post.id}}">
						      		<button>
						      			{% if request.user in post.post_users_like %}
						      			<i class='la la-thumbs-down la-like--action-icon unliked'></i>
						      			{% else %}
						      			<i class='la la-thumbs-up la-like--action-icon liked'></i>
						      			{% endif %}
						      		</button>
						      		<span class="like-text icon-text">Like</span>
						      	</form>
						      	{% else %}
						      	<form action="" method="" class="like-form">
						      		<button>
						      			<i class='la la-thumbs-up la-like--action-icon unliked'></i>
						      		</button>
						      		<span class="like-text icon-text">Like</span>
						      	</form>
						      	{% endif %}
						      	<span class="action-comment-span space-action-span comment-action-js">
						      		<i class='la la-comments la-comment-action-icon'></i>
						      		<span class="comment-text icon-text">Comment</span>
						      	</span>
						      	<span class="action-share-span space-action-span">
						      		<i class='la la-share la-comment-action-icon'></i>
						      		<span class="share-text icon-text">Share</span>
						      	</span>

						      	<!-- <span class="float-right icon-text" data-toggle="modal" data-target="#exampleModalScrollable">Top Comments<i class='la la-caret-down'></i></span> -->
						      </div>
						      {% include 'partials/_top_comments_modal.html' %}
						      <!-- comment form div -->
						   {% if is_auth %}
						  	<div class="comment-form-div hide-comment-form-wrap">
						      	<div class="container-fluid comment-container--fluid-padding">
						      		<div class="row">
						      			<div class="col col-lg-2">
						      				{% if request.user.profile.pic %}
						      				<img src="{{request.user.profile.pic_url}}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% else %}
						      				<img src="{% static 'images/request_user.png' %}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% endif %}
							      		</div>
						      			<div class="col col-lg-10">
						      				<form class="form-inline my-2 my-lg-0 comment-form" action="{% url 'comment:comment-add' %}" method="POST">
						      					{% csrf_token %}
						      					<!-- <div class="col-lg-12"> -->
						      						<input type="hidden" name="post_id" value="{{post.id}}">
								      				<input class="form-control mr-sm-2 form-control-lg comment-input" type="search" placeholder="Add a comment...">
								      			<!-- </div> -->
								    		</form>
						      			</div>
						      		</div>
						      		{% if post.recent_post_comment %}
						      		<div class="row space-posts-comments-by-users">
						      			<div class="col col-lg-2">
						      				{% if post.recent_post_comment.user.profile.pic %}
						      				<img src="{{post.recent_post_comment.user.profile.pic_url}}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% else %}
						      				<img src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="..." class="avatar-comment-sizing rounded-circle">
						      				{% endif %}
							      		</div>
						      			<div class="col col-lg-10">
						      				<div>
						      						{% if post.recent_post_comment.user%}
						      						<h6>
						      					      <a href="{{post.recent_post_comment.user.profile.get_absolute_url}}"> {{post.recent_post_comment.user.username}}</a>
						      				    	</h6>
						      				        {%endif%}
						      					<div class="post-comment-text-wrap clearfix">
						      						<p>
						      							{{post.recent_post_comment.content}}
						      						</p>
						      						<p class="float-right">{{ post.recent_post_comment.readable_time }}</p>
						      					</div>
						      				</div>
						      			</div>				      			
						      		</div>
						      		{% endif %}
								</div>
						      </div>
						      {% endif %}
						      <!-- close comment form div -->
						    </div>
						  </div><!-- card end -->
		</div><!-- / col-lg-5 card content -->

		<!-- Right -->
		<div class="col-lg-5">
			<div class="card">
			  <div class="card--title">
			  	<h4>Comments</h4>
			  	<div class="comment-underline"></div>
			  </div>
			  {% if comments %}
				  {% for comment in comments %}
					  <div class="card-body post-comment-wrap">
					  	{% if comment.user.profile.pic %}
					  	<img src="{{ comment.user.profile.pic_url }}" alt="" style="width: 70px;height: 70px;max-width: 100%;border-radius: 50%;display: inline-block;vertical-align: top !important;"/>
					  	{% else %}
					    <img src="{% static 'images/avatar/default_avatar.jpeg' %}" alt="" style="width: 70px;height: 70px;max-width: 100%;border-radius: 50%;display: inline-block;vertical-align: top !important;"/>
					  	{% endif %}

						    <div class="comment-content">
						    	<p class="username-parag"><a href="{{comment.user.profile.get_absolute_url}}">{{ comment.user.username }}</a></p>
						    	<p>{{ comment.content }} .<span class="time-reads">{{comment.readable_time}}</span></p>

						    	{% if is_auth %}
							    	{% ifequal post.owner request.user %}
									    <form action="{% url 'comment:comment-remove' %}" method="POST" style="display: inline-block;" class="comment-remove-form">
									      {% csrf_token %}
									      <input type="hidden" name="comment_id" value="{{ comment.id }}">	
									      <button type='submit' class="badge badge-danger">remove comment</button>
									    </form>
								    {% endifequal %}
							    {% endif %}
						    </div>
					  </div>
				  {% endfor %}
			  {% else %}
			  <p class="no-comments">No Comments can be found for this post.</p>
			  {% endif %}
			</div>
		</div>
		<!-- /Right -->
	</div>
</div>
{% endblock %}